Products/zms/standard.py

This reverts d3044e01 and 51e1f7a2

Removed merge duplication

---

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js

Added ZMI styling for timepicker #8

Added timepicker to DateTimeInput

---

Products/zms/ZMSMetaobjManager.py

Fix von Records-Set: custom muss ins XML

ZMSRecordSet: Configuration for displaycol is lost #11

---

Products/zms/standard.py
Products/zms/zmssqldb.py

some minor refactorings of zmssqldb

refactoring of zmssqldb

---

Products/zms/_objattrs.py

fixed local activity in primary lang:
primary lang always defaults activity to 1

fixed local activity in primary lang

---

Products/zms/standard.py

Removed semicolon, already set in line before

---

Products/zms/conf/metaobj_manager/com.zms.foundation.bootstrap/bt_link_list/__init__.py
Products/zms/conf/metaobj_manager/com.zms.foundation.bootstrap/bt_link_list/interface0.dtml
Products/zms/conf/metaobj_manager/com.zms.foundation.bootstrap/bt_link_list/interface0.zpt
Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js

Breadcrumbs not showing up in url-inputs of table in bootstrap-link-list

Bootstrap-Link-List: fixed breadcrumbs

---

Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTable/__init__.py
Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTable/standard_html.zpt

replaced UZK residual by BS "table-responsive"

fixed ZMSTable class name

---

Products/zms/ZMSMetaobjManager.py

Improved support for langdict ex-/import from #33 
Find enclosed a simple mechanism to export and import language dictionaries of a specific content class using the ZMSRepositoryManager.
Skip manual resource-attribute ‘langdict.xml’ and export lang-dict to __init__.py (analogue to xml-ex-/import).
#33 seemed to be incomplete since import into the language dictionary was missing.

ZMSRepoManager: Added support for langdict ex-/import

---

Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSObjectSet/script.zmi.js
Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js

Fix auto-insert in empty content objs

---

Products/zms/_versionmanager.py

fixed ref_to for new objects

---

Products/zms/import/_language.xml
Products/zms/plugins/www/zmi.core.css
Products/zms/zpt/ZMSFilterManager/manage_main.zpt
Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt
Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
Products/zms/zpt/ZMSMetamodelProvider/manage_metas.zpt

changed hidden well blocks to tooltips (to be continued ;-)

cleaned BS3 well css class

---

Products/zms/ZMSMetaobjManager.py
Products/zms/_mediadb.py
Products/zms/_objattrs.py
Products/zms/_pathhandler.py
Products/zms/_zmi_actions_util.py
Products/zms/conf/metaobj_manager/com.zms.foundation.bootstrap/bt_scrollspy/__init__.py
Products/zms/conf/metaobj_manager/com.zms.foundation.bootstrap/bt_scrollspy/standard_html.zpt
Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Products/zms/plugins/www/zmi.core.css
Products/zms/standard.py
Products/zms/zmscustom.py
Products/zms/zmsindex.py
Products/zms/zmsobject.py
Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
Products/zms/zpt/ZMSObject/input_fields.zpt
Products/zms/zpt/ZMSObject/manage_main.zpt
Products/zms/zpt/ZMSObject/manage_main.zpt:Zone.Identifier
Products/zms/zpt/ZMSRecordSet/grid.zpt
Products/zms/zpt/objattrs/f_select_file.zpt
Products/zms/zpt/objattrs/f_select_image.zpt

First prototype of new ZMSRecordGrid. This is very similar to ZMSRecordSets. Only the interface is much simpler. If you want to edit a small number of columns in a single grid this might be easier to use.

ZMSRecordGrid

---

Products/zms/zmsobject.py

removed / from absolute_url after condition check

removed / from absolute_url

---

Products/zms/plugins/www/object/manage_menu.js

Fixed ZMI-Sitemap navigation for domains that differ from the frameset domain to avoid problems whith manage_ajaxZMIActions

Fixed ZMI-Sitemap navigation

---

Products/zms/conf/metacmd_manager/manage_attrChange/__init__.py
Products/zms/conf/metacmd_manager/manage_attrChange/manage_attrChange.py
Products/zms/conf/metacmd_manager/manage_searchReplace/__init__.py
Products/zms/conf/metacmd_manager/manage_searchReplace/manage_searchReplace.py

Req by UniBE https://github.com/idasm-unibe-ch/unibe-cms-frontend/issues/175

added multiautocomplete type to attr change action

---

Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTextarea/__init__.py
Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTextarea/interface0.zpt

HTML invalidity may due to the extensive usage of HTML inline elements. ZMSTextarea now checks HTML code while entering and provides a status info permanently. In case the text stream contains invalid HTML the click on save-button requires an explicit confirmation. The check is done by DOMParser(): https://developer.mozilla.org/en-US/docs/Web/API/DOMParser

Realtime HTML Validity Info

---

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Products/zms/plugins/www/object/manage_menu.js
Products/zms/plugins/www/zmi.core.css
Products/zms/zpt/object/manage_menu.zpt

The bookmark icons did not show up in the sitemap menu. CSS-classes and JS are fixed/updated,

fixed bookmark menu

---

Products/zms/_blobfields.py

return decoded string instead of bytes

file-attributes: str - return decoded string instead of bytes (#121)

---

Products/zms/zpt/common/zmi_html_head.zpt

improving multi-tab browser orientation by naming the short title instead of unspecific display_type

More Specific ZMI Browser Titles

---

Products/zms/ZMSMetaobjManager.py
Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt

Alternative approach to https://github.com/zms-publishing/ZMS/pull/134

Zope5.8.3: Handling missing Metobj-Manager fileuploads (#130) 

---

Products/zms/ZMSMetacmdProvider.py
Products/zms/ZMSMetaobjManager.py
Products/zms/ZMSRepositoryManager.py
Products/zms/conf/metacmd_manager/manage_addClient/manage_addClient.py

handle acquired artifacts with repository-manager
Reference: https://github.com/idasm-unibe-ch/unibe-cms-frontend/issues/270

handle acquired artifacts with repository-manager

---

Products/zms/_exportable.py
Products/zms/_fileutil.py
Products/zms/_filtermanager.py
Products/zms/_importable.py
Products/zms/_mediadb.py
Products/zms/import/docx.metacmd.xml
Products/zms/pilutil.py
Products/zms/standard.py
tests/test_standard.py

Fix Security Issues
https://github.com/zms-publishing/ZMS/security

Fix Security Issues

---

Products/zms/_pathhandler.py
Products/zms/mock_http.py
Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Products/zms/rest_api.py
docs/develop_intro_en.md
tests/test_accessmanager.py
tests/test_rest_api.py
tests/test_zmscontainerobject.py
tests/test_zmsindex.py
tests/zms_test_util.py

Implemented Headless API (in analogy to Restful API).
Please refer to tests, e.g.:
```
headless = rest_api.RestApiController()
actual = headless.get(document)
self.assertTrue(isinstance(actual, dict))
self.assertEqual( actual['meta_id'], 'ZMSDocument')
```

Headless API

---

Products/zms/_mediadb.py

Huge media-folders are often not replicated into dev environments. To avoid permanent error messages, now a dummy file will be retuned  in case the file cannot be found in the file system.

Return dummy file in case of missing media-folder file

---

Products/zms/_zreferableitem.py

Refactoring:
synchronize code in if and else

Fix #172 resolve default url

---

Products/zms/zmsobject.py

fixed duplicate execution of meta-cmds

fixed duplicate execution of meta-cmds (#404)

---

Products/zms/__init__.py
Products/zms/standard.py

Ensure containers for temporary data in Product initialization

Ensure containers for temporary data

---

Products/zms/zmsobject.py

fixed duplicate execution of meta-cmds and fixed tabs

fixed duplicate execution of meta-cmds (2)

---

Products/zms/zpt/ZMSFilterManager/manage_main.zpt

The online code preview of py script are too similar because of head comments. Now tooltip shows more:

ZMS Filter: improved code preview

---

Products/zms/__init__.py

Refs https://github.com/zms-publishing/ZMS/pull/187/files/3c3427b922957e52a156d46c6dcf8e68ec39a8d0#r1341343451

Add ZODBMountPoint temp_folder if available

---

Products/zms/ZMSFilterManager.py
Products/zms/zpt/ZMSFilterManager/manage_main.zpt

Adding as new process step into the sequence is instable. I added the JS function for row-inserting derived from metamodel-gui

Filter-GUI

---

Products/zms/ZMSMetacmdProvider.py
Products/zms/ZMSRepositoryManager.py
Products/zms/ZMSZCatalogOpensearchConnector.py
Products/zms/_confmanager.py
Products/zms/conf/metacmd_manager/manage_zcatalog_export_schema/manage_zcatalog_export_schema.py
Products/zms/conf/metaobj_manager/com.zms.foundation.zcatalog.opensearch/__init__.py
Products/zms/conf/metaobj_manager/com.zms.foundation.zcatalog.opensearch/opensearch/__init__.py
Products/zms/conf/metaobj_manager/com.zms.foundation.zcatalog.opensearch/opensearch/add_docmt_to_opensearch_index.py
Products/zms/conf/metaobj_manager/com.zms.foundation.zcatalog.opensearch/opensearch/beforeCommitObjChangesEvt.py
Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt
Products/zms/zpt/ZMSRepositoryManager/manage_main_diff.zpt
Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt
Products/zms/zpt/ZMSZCatalogAdapter/manage_opensearch_connector.zpt

Export/Import Opensearch-Schema with ZMS5-Repository

Export/Import Opensearch-Schema with ZMS5-Repository

---

.vscode/ZMS5.code-workspace
Products/zms/ZMSZCatalogAdapter.py
Products/zms/ZMSZCatalogConnector.py
Products/zms/ZMSZCatalogSolrConnector.py
Products/zms/conf/metacmd_manager/manage_addClient/manage_addClient.py
Products/zms/conf/metacmd_manager/manage_opensearch_export_data_paged/__init__.py
Products/zms/conf/metacmd_manager/manage_opensearch_export_data_paged/manage_opensearch_export_data_paged.py
Products/zms/conf/metacmd_manager/manage_zcatalog_create_sitemap/manage_zcatalog_create_sitemap.py
Products/zms/conf/metacmd_manager/manage_zcatalog_export_data/manage_zcatalog_export_data.py
Products/zms/conf/metacmd_manager/manage_zcatalog_export_schema/manage_zcatalog_export_schema.py
Products/zms/conf/metacmd_manager/manage_zcatalog_update_documents/manage_zcatalog_update_documents.py
Products/zms/conf/metacmd_manager/manage_zmsindex_reindex_paged/__init__.py
Products/zms/conf/metacmd_manager/manage_zmsindex_reindex_paged/manage_zmsindex_reindex_paged.py
Products/zms/conf/metaobj_manager/com.zms.foundation.zcatalog.opensearch/opensearch/add_docmt_to_opensearch_index.py
Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSObjectSet/script.zmi.js
Products/zms/content_extraction.py
Products/zms/standard.py
Products/zms/zmscontainerobject.py
Products/zms/zmsindex.py
Products/zms/zpt/ZMSIndex/manage_main.zpt
Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt

The Reindex-GUI (metacmd: [manage_opensearch_export_data_paged](https://github.com/zms-publishing/ZMS/tree/main/Products/zms/conf/metacmd_manager/manage_opensearch_export_data_paged )) needs more options:
1. Recursive ZMS-Cients
2. Parse Binary-Files

Opensearch-Integration: Paged-Reindexing for FileBinaries

---

.vscode/settings.json
Products/zms/ZMSMetacmdProvider.py
Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt

Refs #207, https://github.com/idasm-unibe-ch/unibe-cms/pull/435#issuecomment-1793782441

ZMSMetacmd: Try to handle errors in External Methods

---

Products/zms/_mediadb.py
Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Products/zms/zpt/ZMS/manage_customize.zpt

Show status / usage for media-folder, e.g.:
foo_2023112812345.png => /e1/e2/ZMSFile:file
foo_2023112812346.png => /e3/ZMSFile:file
foo_2023112812378.png => /e6/e8/e9/ZMSFolder:titleimage

Media-Folder: show status / usage

---

Products/zms/ZMSZCatalogAdapter.py
Products/zms/zmsobject.py
Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt

renamed get_connectors and verified broken-objects fix.
broken-objects can't be deleted automagically since they do not have an id :-(

get_connectors

---

Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/__init__.py
Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/__init__.py
Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/opensearch_suggest.py

Reference: "Autocomplete-Suggestions with SQL"
https://github.com/idasm-unibe-ch/unibe-cms/blob/unibe/opensearch/docs/notebooks/unibe_multisearch.ipynb

opensearch: multiindex autosuggest terms

---

Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/__init__.py
Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/opensearch_suggest.py
Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/readme
Products/zms/zpt/ZMSZCatalogAdapter/manage_zcatalog_connector.zpt

Added config parameter `opensearch.suggest.fields.$index_name` for defining the source attributes for suggesting search terms

Opensearch: Configuration Suggestion Terms Source 

---

Products/zms/conf/metacmd_manager/manage_searchReplace/__init__.py
Products/zms/conf/metacmd_manager/manage_searchReplace/manage_searchReplace.py

Fixes https://github.com/idasm-unibe-ch/unibe-cms/issues/446

Search+Replace: Error handling, Loading spinner, Content class grouping

---

Products/zms/conf/metacmd_manager/manage_searchReplace/__init__.py
Products/zms/conf/metacmd_manager/manage_searchReplace/manage_searchReplace.py

Builds upon
- #234 
Adds new feature
- new default set to case-insensitive search
- new checkbox added to activate case-sensitive search as before

Search+Replace: Case-insensitive 

---

Products/zms/_zmi_actions_util.py
Products/zms/_zreferableitem.py
Products/zms/conf/metacmd_manager/manage_zmsindex_reindex/__init__.py
Products/zms/conf/metacmd_manager/manage_zmsindex_reindex/manage_zmsindex_reindex.py
Products/zms/standard.py
Products/zms/zmscontainerobject.py
Products/zms/zmsindex.py
Products/zms/zmsobject.py
Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt

Improved performance of paged reindex

ZMSIndex Reindex

---

Products/zms/zpt/ZMS/manage_customize_diff.zpt

This PR adds a switch to display/include new elements (aka 'respect or ignore orphans').

feat(customize-diff): Added switch to display new elements

---

Products/zms/_conf.py
Products/zms/_confmanager.py

**IMPORTANT NOTE:
Please use with care. The branch creates a new object class ZMSSysConf that allows (at the moment) no downgrade anymore or lossless switch back in main branch.**
Export/Import System-Configuration to Repository
Known limitations:
- not very well formatted dict
- passwords are not encrypted (possible security-issue!)
- full export of all properties, filter and merge may be necessary later

System-Configuration Repo

---

Products/zms/zmsobject.py
Products/zms/zpt/ZMS/index.zpt

Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/587
trashcan will force any subsequent content as invisible

HTTP 404 Not Found for objects in trashcan

---

Products/zms/ZMSZCatalogAdapter.py
Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/manage_opensearch_objects_remove.py
Products/zms/content_extraction.py
Products/zms/zmscontainerobject.py

Refact re- and un-indexing according to different types of node changes:
More details here: https://github.com/zms-publishing/ZMS/issues/278

Incremental Reindexing on Change/Insert/Delete

---

Products/zms/conf/metaobj_manager/com.zms.catalog.zcatalog/zcatalog_connector/__init__.py
Products/zms/conf/metaobj_manager/com.zms.catalog.zcatalog/zcatalog_connector/manage_zcatalog_objects_add.py

fix multilingual indexing for ZCatalog-Connector:
retrieve lang from data instead of request

ZCatalog-Connector multilang-indexing

---

Products/zms/import/LgEmployeeRecordSet.content.xml
Products/zms/import/LgEmployeeRecordSet.metaobj.xml
Products/zms/zmscustom.py
Products/zms/zpt/ZMSRecordSet/main.zpt
Products/zms/zpt/common/zmi_breadcrumbs.zpt

Recalibrate qindex only in context of grid

fixed recordset filtering, reduced filter amounts / session data (2)

---

Products/zms/_xmllib.py

Ref: https://github.com/zms-publishing/ZMS/issues/298

type-fix: index on dict.keys

---

Products/zms/zms.py

Block each ZODB transaction except "ZMS.mode.maintenance" changes.

Maintenance: Block each ZODB transaction in maintenance mode

---

Products/zms/_cachemanager.py
Products/zms/zmsobject.py

Ref: https://github.com/zms-publishing/ZMS/issues/316

improved performance of headless requests

---

Products/zms/_accessmanager.py

Refresh View management screens by calling synchronizeRolesAccess

synchronizeRolesAccess: View management screens (ii) #254

---

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js

Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/465
Blame: https://github.com/zms-publishing/ZMS/commit/ce4f7ff8c1c394a78c96c63ac92015312ad3e194

CK Editor: Document-links not editable #465

---

.vscode/launch.json
Products/zms/repositoryutil.py

Use namespaces for exec:
https://docs.python.org/3/whatsnew/3.13.html
https://docs.python.org/3/library/functions.html#exec

Py-3.13: fix tests due to failing __init__.py

---

Products/zms/zpt/ZMSObject/input_fields.zpt
Products/zms/zpt/ZMSRecordSet/grid.zpt
Products/zms/zpt/ZMSRecordSet/main.zpt
Products/zms/zpt/ZMSSqlDb/manage_main.zpt

New Features
- added `readme` to ZMSRecordSet main and grid view
- render constant/string `readme` as well
References
- #139
- #202 
- 7646692976f0d18c355a1e7419b04178963fefbc

feat(readme): Extended markdown rendering

---

Products/zms/_zreferableitem.py

Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/809

Monotonize mailto-link obfuscation

---

Products/zms/zpt/ZMSObject/input_fields.zpt
Products/zms/zpt/ZMSRecordSet/grid.zpt
Products/zms/zpt/ZMSRecordSet/main.zpt
Products/zms/zpt/ZMSSqlDb/manage_main.zpt

Refs
- #348
Fixes https://github.com/idasm-unibe-ch/unibe-cms/issues/834

fix(readme): Fixed markdown rendering on insert

---

Products/zms/conf/metacmd_manager/manage_zmsindex_reindex/__init__.py
Products/zms/zpt/ZMSIndex/manage_main.zpt

Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/839

Handle zmsindex-actions as additional options in ZMSIndex-GUI

---

Products/zms/_objattrs.py

Ref: 
https://github.com/idasm-unibe-ch/unibe-cms/issues/850
https://docs.python.org/3/library/time.html#time.struct_time.tm_isdst
https://docs.python.org/3/library/time.html#time.daylight

Fixed determination of dst (daylight saving time)

---

Products/zms/conf/metacmd_manager/manage_export_pydocx/manage_export_pydocx.py
Products/zms/conf/metacmd_manager/manage_export_pydocx/play.ipynb

Added handling for inline images and HTML-element or entities in headlines

DOCX-Export: Refinements

---

Products/zms/import/_language.xml
Products/zms/zmstrashcan.py
Products/zms/zpt/ZMSTrashcan/manage_properties.zpt

Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/907#issuecomment-2778930101

Garbage Collection Terminology

---

Products/zms/_versionmanager.py

Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/916#issuecomment-2795309208

getObjVersion(): avoid error on missing version attributes

---

Products/zms/_copysupport.py

Ref:
* https://github.com/zms-publishing/ZMS/issues/396
* https://github.com/idasm-unibe-ch/unibe-cms/issues/886
* https://github.com/zms-publishing/ZMS/pull/331

OpenSearch: Re-Indexing too early for doublicated of page elements #396

---

Products/zms/zmssqldb.py

Ref: https://github.com/sntl-projects/neon/issues/21

Fix ZMSSqlDb.execute
