Products/zms/_objinputs.py
ZMSMetaobjManager.valid_types include `time` but it the input field does not render properly in ZMI: the datepicker is shown instead of a timepicker.
=> Added timepicker to DateTimeInput

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
With the Firefox browser `type=date` is set in any case. So instead of a timepicker a datepicker is shown with `type=time`.
This patch fixes this behaviour and adds a switch back between `date` and `datetime-local` on double click.
Workaround is needed because picker for type=datetime-local is broken in Firefox
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local
=> Fixed timepicker in Firefox workaround

Products/zms/import/com.zms.foundation-4.1.0.metaobj.xml, Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSObject/input_fields.zpt
Hi @zmsdev ,
complex sub-elements of "special" content classes didd not appear in the typical grid layout.  This change https://github.com/zms-publishing/ZMS5/commit/c6fecb8a5188ebd652c77dfa6ffdcc1496dbde51 tried to fix it by CSS, but there is still a visual discrepancy between the cases hasChildren vs. not:hasChildren.
So I monotonized it (picture);  the cases hasChildren vs. not:hasChildren are still seperated in the TAL code. Maybe this not necessary and zpt/ZMSObject/input_fields.zpt  could get shorter. Any ideas?
=> ZMI: monotonized complex input fields

Products/zms/ZMSMetaobjManager.py, Products/zms/_globals.py, Products/zms/zmssqldb.py, Products/zms/zpt/ZMSRecordSet/main_grid.zpt, Products/zms/zpt/ZMSSqlDb/manage_main.zpt
Hello @zmsdev,
The zmssqldb-colType mapping refers to the basic types ZSQLMethods provides as parsed:
https://github.com/zopefoundation/Products.ZSQLMethods/blob/2c2d9799937868611135678b47d39275072a159e/src/Shared/DC/ZRDB/RDB.py#L40
Unluckily the fact, that many database field types do not refer to the parsed types we get a a huge amout of error log entries of any grid rendering. 
What about declaring the unparsed tpyes as string? 
Picture shows the two locations: e.g. you can see, that "l"/Long is mapped as string:
=> declare unidentified coltypes as string

Products/zms/zmsobject.py
New method ZMSObject.getAbsoluteUrlInContext(self, context, index_html=None) defaulting to absolute_url()
Usage of subdomain can be activated with the conf-property ZMSObject.getAbsoluteUrlInContext=True
=> UzK: Navigation links in ZMI with the configured subdomain instead absolute_url #23

Products/zms/zmscustom.py, Products/zms/zpt/ZMSRecordSet/main_grid.zpt
ZMSRecordSets provide an easy method to model and manage the collection of tabular data.
I propose to add a CSV export for further processing of the entered data. My pull request relies on the third-party library https://github.com/martinblech/xmltodict to extend the existing XML export with just a few lines.
Question:
Are there any plans to modularize the code of ZMSRecordSet as well as it has been done with other content objects at https://github.com/zms-publishing/ZMS5/tree/master/Products/zms/conf/metaobj_manager/com.zms.foundation (this would simplify extension and customization)?
=> ZMSRecordSet: Add CSV Export

Products/zms/ZMSMetaobjManager.py, Products/zms/conf/metaobj_manager/zms.formulator/zms.formulator.lib/JSONEditor.py, Products/zms/conf/metaobj_manager/zms.formulator/zms.formulator.lib/__init__.py, Products/zms/conf/metaobj_manager/zms.formulator/zms.formulator.lib/getJSONEditor.py, Products/zms/conf/metaobj_manager/zms.formulator/zms.formulator.lib/langdict.xml
Find enclosed a simple mechanism to export and import language dictionaries of a specific content class using the ZMSRepositoryManager.
Prerequisite is an attribute ‘langdict.xml’ of type resource, which has to be applied manually to the content class definition. If this attribute exists, all language entries of this content class (with its ID as prefix) will be exported as XML - and vice versa imported into the language dictionary.
As an example I revised the langdict.xml of zms.formulator and its used keys.
=> ZMSRepoManager: Added support for langdict ex-/import

Products/zms/ZMSMetaobjManager.py, Products/zms/ZMSRepositoryManager.py, Products/zms/conf/metaobj_manager/com.zms.index/__init__.py, Products/zms/standard.py, Products/zms/zopeutil.py
Referring to Issue #34 there are imho 2 critical sections in ZMSRepositoryManager.getDiff():
1. Checking whether the stream can considered as code stream or a not-comparible byte stream: https://github.com/zms-publishing/ZMS/blob/016e12b39b7eec4074cb86d9cd89700c5428a110/Products/zms/ZMSRepositoryManager.py#L221-L225
2. and the file type guessing https://github.com/zms-publishing/ZMS/blob/016e12b39b7eec4074cb86d9cd89700c5428a110/Products/zms/ZMSRepositoryManager.py#L236-L242
I suggest to enter the filetype guessing (which should be applied only on files having confirmed diffs) with the original data (set as a variable) instead of try-ing to encode data back. 
https://github.com/zms-publishing/ZMS/blob/55373f789fbc5ce5205512a4e1847b16f2bca11c/Products/zms/ZMSRepositoryManager.py#L219-L222 …
=> Repomanager-Diff: reduce encoding errors 

Products/zms/_zmi_actions_util.py
Added condition to suppress the menu item 'copy' for objects placed in the trashcan (Ref: IDCMS-335)
wthout fix
with fix
=> avoid copy form trashcan (UniBE)

Products/zms/plugins/www/common/zmi_ace_editor.js, Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt, Products/zms/zpt/common/zmi_ace_editor.zpt
This a feature mockup is a UX proposal: on dblclick the content modeller's code editor changes from the plain to the ACE code editor. A link to the Zope editor (which was reached by dblclick before) may be added.
The zmi-ace-editor JS should made more flexible and support multiple ACE instance on a page.
=> metamodeller shows ace editor on dblclick

Products/zms/standard.py
I propose a change of the signature of method `standard.http_request`.
IMHO the `headers` parameter has no effect on calling `requests` [api methods](https://docs.python-requests.org/en/latest/api/) at the moment. 
Using `**kwargs` introduces the most flexibility and should preserve the current usage in [metacmd_manager.manage_zcatalog_update_documents](https://github.com/zms-publishing/ZMS/blob/main/Products/zms/conf/metacmd_manager/manage_zcatalog_update_documents/manage_zcatalog_update_documents.py#L40) - but I think the parameter
`data=data` has to be changed into `files=data`...
Additionally I have added a new option for `method == PURGE`.
=> http_request: Revised method signature and added PURGE

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/plugins/www/zmi.core.css, Products/zms/zmsobject.py, Products/zms/zpt/ZMSContainerObject/manage_main.zpt, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt, Products/zms/zpt/ZMSObject/input_fields.zpt, Products/zms/zpt/ZMSRepositoryManager/manage_main_diff.zpt
If 'deprecated' is added to the icon's stylesheet class, the item is displayed strikethrough in meta overviews and action lists.
=> Added visual indication on deprecated objs/cmds

Products/zms/zpt/ZMSRepositoryManager/manage_main.zpt
If the new system property 'ZMS.conf.paths' is preset with a comma-separated list of repository paths, these items will be selectable to change.
=> RepoManager: Added select list for path

Products/zms/zpt/ZMSFilterManager/manage_main.zpt, Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt, Products/zms/zpt/ZMSWorkflowProvider/manage_main.zpt, Products/zms/zpt/common/zmi_ace_editor.zpt
Turbolinks has some bad interferences with the zms-core JS libs. Mainly Turbolinks results in a 2x call if ACE is rendered in a modal-win:
The concepts are described here;
https://www.honeybadger.io/blog/turbolinks/
In Bootstrap-Modal-Win the ACE-Editor may not initialized correctly. In most cases the the atrtibute `data-turbolinks="false" `on  a-element will help. 
But not with the filter-methods Any ideas?
=> Fix ACE-Editor in ModalWin

Products/zms/zms.py, Products/zms/zpt/ZMS/manage_customize.zpt
This avoids unwanted custom zms_version infos in xml exports.
=> Show custom version from env/git in system info only

Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSContainerObject/zmi_manage_main_change.zpt
Showing the _titleimage_ by backgroud-image/url does not work with movies as a pure CSS solution. Even with static pictures shown as `background-image` there are some problems due to browser limitations (Ref: https://stackoverflow.com/questions/26967890/css-set-background-image-by-data-image-attr): image-URLs needs to be transformend into a full string variable including the "url()" function nesting. If using movie pure css will not work and JS is needed; to simplify the access to the media url now it is added as a `data-attribute`. 
The zmi core CSS will render the video-tag in the right column similar to the image preview.
But an addiitional custom JS function is needed to show video preview on `mouseover`. It may look like this:
```javascript
$('.titleimage-preview').each( function() { …
```
=> zmi: added titleimage as data attr

Products/zms/_globals.py, Products/zms/standard.py, docs/notebooks/snippets_01.ipynb
hi @zmsdev,
sorting a data-grid by struct_time fields may result in a incorrect order:
my code proposal addresses the struct_time type and transforms it into a sortable number:
Change: https://github.com/zms-publishing/ZMS/compare/main...fix_structime_sorting#
https://github.com/zms-publishing/ZMS/blob/324b7160e38fdc1a5653d04a71b64509bbb40d47/Products/zms/_globals.py#L107-L116
Background: the _sort_list_()-function uses the _sort_item_()-function to normalise the sortable values
=> sort_list(): fixed sorting of struct_time fields

Products/zms/conf/metaobj_manager/com.zms.calendar/__init__.py, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar/__init__.py, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar/get_calendar.py, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar/get_events.py, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar/standard_html.zpt, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar/test__calendar__get_events.py, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar_items/__init__.py, Products/zms/conf/metaobj_manager/com.zms.calendar/calendar_items/standard_html.zpt, docs/notebooks/snippets_02.ipynb
Using python standrd lib calendar for generating a table grid calender als ZMS content object primarily allowing to edit events in a simple ZMS datatable.
_References:_
1. https://docs.python.org/2.7/library/calendar.html#calendar.HTMLCalendar
2. https://docs.python.org/3.8/library/calendar.html#calendar.HTMLCalendar
Work in progress (V0.0.1)
IMPORTANT NOTE: first install your OS locale pack, e.g.
`sudo apt-get install language-pack-de-base`
=> added pythonic calendar content object

Products/zms/ZMSRepositoryManager.py
Hello @zmsdev ,
syncing with repomanager may end up in cycles of im/export because Zope removes trailing whitespace while some editors may add a final line-break. To avoid these false positive diffs I suggest to strip() the code before diffing.
The effect canbe seen on the following pics: the final line-break will not taken into account anymore.
1. ![EOL_0](https://user-images.githubusercontent.com/29705216/179298559-ffb4dac4-ce47-4a42-9e4c-90cb2c8a8e75.gif)
2. ![EOL_1](https://user-images.githubusercontent.com/29705216/179298568-da96fadc-d357-429b-a99d-d71679d07367.gif)
3. ![EOL_2](https://user-images.githubusercontent.com/29705216/179298577-5dc76969-18a6-4578-923e-553b7d8f0971.gif)
=> repomanager: ignore leading/trailing whitespace for diff

Products/zms/conf/metaobj_manager/zms.formulator/ZMSFormulator/__init__.py, Products/zms/conf/metaobj_manager/zms.formulator/ZMSFormulator/javscriptandstyle.zpt, Products/zms/conf/metaobj_manager/zms.formulator/ZMSFormulatorItem/__init__.py, Products/zms/conf/metaobj_manager/zms.formulator/ZMSFormulatorItem/interface.dtml, Products/zms/conf/metaobj_manager/zms.formulator/__init__.py, Products/zms/conf/metaobj_manager/zms.formulator/zms.formulator.lib/__init__.py, Products/zms/conf/metaobj_manager/zms.formulator/zms.formulator.lib/langdict.xml
Importing the ZMSFormualator conf is blocked due an XML parse error of langdict.xml. This happens only if langdict.xml is part of the model. Removing it (by comments in init.py) results in a correct import. 
A systematic use CATAdid not solve the XML error on import:
```
<item key="(.*)">(?!<)(.*)</item> ==>
<item key="$1"><![CDATA[$2]]></item>
```
actually removing CDATA from language.xml avoids the error:
```
<item key="(.*)"><!\[CDATA\[(.*)\]\]></item>
<item key="$1">$2</item>
```
With the fix the file language.xml can imported separatly. 
But the lang-items, although part of the model (zms.formulator.lib/_init.py) are not visible in the ZMI, see following picture:
=> ZMSFormulator: avoid XML parse error on lang dict

Products/zms/_zmi_actions_util.py, Products/zms/manage_addzmscustomform.zpt, Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/zpt/ZMSObject/input_fields.zpt
Hello @zmsdev and others,
we observed when using identical conten class labels or language strings (TYPE_*) for overwrite the class label an unexpected content class may be inserted. 
The reason is that the meta_id is computed by the label-text and this may be ambiguous:
My code proposal is adding the meta_id as a 4th element to the json stream used for rendering the action-lists / menus. This has some consequences for the processing in general because now the additional parameter needs to be considered, but only in case of content insertations. So there are some intereferences with "ZMS actions" or workflow steps , because here the 4th json element is used just as a title tooltip. 
We should discuss the objections. Maybe there other ideas to solve the ambiguity problem of labelling?
=> Using meta-id for action list based insertations

.vscode/ZMS5.code-workspace, Products/zms/standard.py, Products/zms/zpt/ZMS/manage_customize.zpt, Products/zms/zpt/ZMS/manage_customizeinstalledproducts.zpt
Added `pip list` (shows Package version **_AND_** editable Project location if available) as supplementary info for `pip freeze --all` (shows Package version **_OR_** editable Git revision if available).
**CAUTION**: The displayed version of Zope or other packages may be misleading if it was previously installed as an editable package.
The version of an editable package persists for Zope (see also `Control Panel`), even if another Zope version has been post-installed via `pip` (see `site-packages`) – but in fact the editable version is still used by the app server (even if `pip uninstall` was executed before). The version in `site-packages` can only be reactivated if the editable package folder is removed – renaming and cleaning up `.pth` and `.egg-info` is not enough.
To reflect version …
=> System-Info: Revised package display

Products/zms/standard.py
Get Auth from URL for standard.http_import() (was SOLR feasibility).
e.g.: https://foo:bar@solr.zms-service.com/path
extract auth-credentails (username/password) and fix URL
=> Get Auth from URL (for SOLR_URL)

Products/zms/ZMSZCatalogConnector.py, Products/zms/ZMSZCatalogSolrConnector.py, Products/zms/_deprecatedapi.py, Products/zms/plugins/www/zmi.core.css, Products/zms/standard.py, Products/zms/zpt/ZMSMetamodelProvider/manage_bigpicture.zpt, Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt, Products/zms/zpt/ZMSZCatalogAdapter/manage_solr_connector.zpt, Products/zms/zpt/ZMSZCatalogAdapter/manage_zcatalog_connector.zpt
hi @zmsdev,
when adding the SOLR Connector GUI, all the reindexing/recreating actions are executed in parallel; so there was always a long latency until the SOLR indexing started. I fixed it by restricting it to the active card:
https://github.com/zms-publishing/ZMS/blob/4cff0490f7ec2491bd92daedb7c65929dc9c8a40/Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt#L262-L264
Moreover the _query testing_ may deliver an unspecific error/404 and it was unclear where it comes from. That's why I introduced for ZMI a new debug-parameter to the function standard._http_import()_:
https://github.com/zms-publishing/ZMS/blob/4cff0490f7ec2491bd92daedb7c65929dc9c8a40/Products/zms/standard.py#L893-L895
If `debug==1` the http-response is not returned as xml but just as plain-text (because it may be other …
=> SOLR Connector: added debug option

Products/zms/zmslog.py
Hi.
due to ZEO and a specific zope.ini configuration the default event.log file may not be found. I suggest, instead of returning an obscure FileNotFoundError of Zope,  to catch this (common) situation an give some detailed hints how to deal with it. 
DISCUSSION:
If the remote develper is connected to a certain port in a ZEO environment and the event.logs are writte specifically for any port. it may be easy to symlink the corresponding event.log. if the file names are port-specific, in a production system its not clear which port ZEO is using and thus the log file name can not anticipated, In this scenario the zmslog can not be used in genereal.
=> zmslog: catch FileNotFoundError

Products/zms/ZMSRepositoryManager.py, Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSFigure/__init__.py, Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSFigure/standard_html.zpt, Products/zms/import/ZMSFigure-5.0.2.metaobj.xml, Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/zpt/ZMSWorkflowProvider/manage_main.zpt, Products/zms/zpt/ZMSWorkflowProvider/manage_main_acquired.zpt, Products/zms/zpt/objattrs/zmi_select_richtext_standard.zpt
The XML-Stream on manage_ajaxGetChildNodes() was simplified with the transition of ZMS3 to ZMS5. Now the XML strucuture is based in one element and attributes, but no child elements anymore.
The link selector GUI in ZMS did not process this reduced XML correctly and images were not shown anymore.  The fix make it work again:
=> Fixed RTE img/file links

Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTable/__init__.py, Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTable/interface0.zpt, Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTable/standard_html.zpt, Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSTable/widths.py
Hi @zmsdev ,
a content object without mandatory input felds will be inserted automatically (redirect_self), But the strcutured data prefill of ZMSTable is done by an _interface method_ which will not get executed when automatically inserted. So I suggest to the authors to provide da table caption which is useful in any case ;-)
Moreover I cleaned a lot.
=> ZMSTable: set caption field as mandatory

Products/zms/zpt/ZMSIndex/manage_main.zpt
At UniBE with over 500,000 records in `zcatalog_index`, we have noticed extremely long run times when accessing `/unibe/zcatalog_index/manage_catalogView` with Products.ZCatalog==6.3.
This seems to be due to the changed behavior of `catalogView.dtml` with `Products.ZCatalog>5.1`:
https://github.com/zopefoundation/Products.ZCatalog/commit/919bdb104173f1cefddf2e800cf2bd216c7acf92
As a workaround we have found the URL paramter `?filterpath=/` which was introduced in https://github.com/zms-publishing/ZMS/commit/22e17356e64b05c3220559583b39220f9e1a4e8b (2021/02/26).
This reduces the run times by a factor of 14 in our environment:
- `/unibe/zcatalog_index/manage_catalogView` =>  5min 11sec (without filterpath) 
- `/unibe/zcatalog_index/manage_catalogView?filterpath=/` => 22sec
Unfortunately the …
=> ZMSIndex: Added filterpath to avoid empty searches by default

Products/zms/_objattrs.py
=> autocomplete: view all options by "*" (UniBE)

Products/zms/_builder.py, Products/zms/_confmanager.py, Products/zms/zmsindex.py
- trigger ObjectAdded for each imported node and remove ObjectImported with full reindex after xml-import
- ObjectImported is still needed for import of zexp
- new config-keys to enable/disable index on import
=> 92: fix blocked xml-import by full reindex

Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
Hello @zmsdev,
to improve orientation in long select lists of metaobjs the contextual metaobj-class is highlightet now
=> metobjmanager: show selected obid

Products/zms/manage_addzmssqldbform.zpt, Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/zpt/ZMSMetamodelProvider/manage_analyze.zpt
hi @zmsdev ,
there is a prohibitive issue with the analysis/listing of certain object classes that miss certain attributes. Any instance of these classes  e.g. ZMSSQLDB, is not shown in the analysis-list, because the current code generates with `attrIds+subObjectIds` an empty list. 
This although the objects actually have editable attrs like titlealt.
I cannot really find a plausible reason for that  (too restrictive?) filtering, but give a simple fix:
in case of an empty attr list, now these obj node are systematically listed without declaring any attribute. Thus these content instances can be found.
_Screen Image: top without fix, bottom with fix_
=> fix manage_analyze

Products/zms/plugins/www/objattrs/zmi.blob.ZMSGraphic_extEdit.js
ZMSGraphic/img input might drop Cropper. It is not reproduceable for sure. The movie shows the effect:
https://nextcloud.sntl-publishing.com/s/RcErG52J5d8TQ4m/download
Removing line
https://github.com/zms-publishing/ZMS/blob/31d7c71330f77367b502ffd22637a1f56f6c8820/Products/zms/plugins/www/objattrs/zmi.blob.ZMSGraphic_extEdit.js#L302
seems to solve the problem. Any idea, why? Or why this line was needed?
=> Stabilize Cropper Function (UniBE DCMS-628)

Products/zms/ZMSZCatalogConnector.py, Products/zms/_multilangmanager.py, Products/zms/_objattrs.py, Products/zms/_objinputs.py, Products/zms/_versionmanager.py, Products/zms/zmsobject.py, Products/zms/zmssqldb.py, Products/zms/zpt/objattrs/f_select_file.zpt, Products/zms/zpt/objattrs/f_select_image.zpt
In case lang is (unintentionally) set to None by the custom code the ZMI input elements cannot be rendered and provide a rather unspecific error hint:
To avoid this the None case should be covered more explicitly.
Any comments/ideas to the fix?
Cheers
fh
=> ZMI: ensure lang var is not None

Products/zms/conf/metacmd_manager/manage_tab_search/manage_tab_search.zpt, Products/zms/conf/metacmd_manager/manage_tab_tasks/manage_tab_tasks.zpt, Products/zms/import/manage_cachepurge-5.0.0.metacmd.xml, Products/zms/zpt/MediaDb/manage_browse.zpt, Products/zms/zpt/MediaDb/manage_properties.zpt, Products/zms/zpt/ZMS/manage_customize.zpt, Products/zms/zpt/ZMS/manage_customizelanguagesform.zpt, Products/zms/zpt/ZMS/manage_users.zpt, Products/zms/zpt/ZMSContainerObject/manage_importexport.zpt, Products/zms/zpt/ZMSContainerObject/manage_importexportdebugfilter.zpt, Products/zms/zpt/ZMSContainerObject/manage_main.zpt, Products/zms/zpt/ZMSContainerObject/manage_system.zpt, Products/zms/zpt/ZMSFilterManager/manage_main.zpt, Products/zms/zpt/ZMSFormatProvider/manage_charformats.zpt, Products/zms/zpt/ZMSFormatProvider/manage_textformats.zpt, Products/zms/zpt/ZMSIndex/manage_main.zpt, Products/zms/zpt/ZMSLinkElement/manage_refform.zpt, Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt, Products/zms/zpt/ZMSMetamodelProvider/manage_metas.zpt, Products/zms/zpt/ZMSObject/manage_main.zpt, Products/zms/zpt/ZMSRepositoryManager/manage_main.zpt, Products/zms/zpt/ZMSSqlDb/manage_configuration.zpt, Products/zms/zpt/ZMSSqlDb/manage_main.zpt, Products/zms/zpt/ZMSSqlDb/manage_properties.zpt, Products/zms/zpt/ZMSTrashcan/manage_properties.zpt, Products/zms/zpt/ZMSWorkflowProvider/manage_main.zpt, Products/zms/zpt/ZMSWorkflowProvider/manage_main_acquired.zpt, Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt, Products/zms/zpt/objattrs/manage_propertiesform.zpt, Products/zms/zpt/versionmanager/manage_undoversionform.zpt
The footer section was systematically doublicated due to `<footer tal:content=... >` instead of `<footer tal:replace=... >`
=> cleaned doublicated footer element

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
The metobj-manager gui had two sections with its save button: one on the top of the form and the other at the bottom, because the form may be long and the save button may get invisible.
The new css class "sticky-controls" reacts on vertical scrolling and is activated as sticky when leaving the viewport.
=> New CSS class: sticky-controls

Products/zms/_textformatmanager.py
In #125 the SimpleMDE / Markdown Editor was introduced as additional RTE.
To avoid unintended rendering of existing text content as Markdown, I suggest adding a condition.
However, the `ConfProperties` are set for the entire ZMS client, so existing text content in this client will still to be affected.
An additional condition to check the paragraph format or something similar would prevent this...
=> SimpleMDE: Added condition to render markdown

Products/zms/_blobfields.py, Products/zms/_xmllib.py
missing mediafolder file block XML export; the fix prevents that block an missing binarys appear as empty file in the XML stream.
=> try encoding if blob data empty/text

Products/zms/_accessmanager.py, Products/zms/zpt/common/zmi_navbar_brand.zpt
Ref: https://github.com/zms-publishing/ZMS3/commit/478405499868d1ab045215de66b58ee6f2995016
For UnrestrictedUser/Emergency User Zope returns on has_role() constantly True/1:
https://github.com/zopefoundation/AccessControl/blob/f9ae58816f0712eb6ea97459b4ccafbf4662d9db/src/AccessControl/users.py#L311-L312
In this case has_role() prohibits ZMI access.
Actually in Inability to create content is conformant to the idea of Emergency User:
https://zope.readthedocs.io/en/latest/zopebook/Security.html#zope-emergency-user
but not prohibiting ZMI-View
=> fixed access for Zope UnrestrictedUser

Products/zms/ZMSMetaobjManager.py, Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
Hello @zmsdev 
Intermediate saving on adding new attributes to the content model  may not match the user's expectations. Actually it is not very fast. So the ZMI should alllow just a "final" Saving. The code proposal works with JS-cloning of the "add"-row. The cloned TR-element is used as a template that is changed by JS so that it can work like the "old" rows. Thus the backend code can handle it. 
About the JS Code:
The crucial point is that the JS-cloning has to be done _inside_ the  click-event function and the added TR needs an unique ID, to get it selected in the DOM.
A cloning in advance, means outside the funktion, generates one global object which on button-click  will instanciated into itself, so that in the end only one new attribute row can be added.
BTW: the processing of the …
=> Improved ZMSMetaobjManager GUI

Products/zms/_globals.py
the new _globals.sort_item(i) may apply str.replace() on an int.
=> sort_item(): Type Error

Products/zms/zopeutil.py
Acquired External Methods cannot be located by diff processing. This is a quickfix to avoid blocking the Repomanager GUI.
=> handle missing ext methods in repomanager

Products/zms/ZMSRepositoryManager.py, Products/zms/_accessmanager.py, Products/zms/_confmanager.py, Products/zms/_objattrs.py, Products/zms/_objinputs.py, Products/zms/_xmllib.py, Products/zms/_zreferableitem.py, Products/zms/zms.py, Products/zms/zmsindex.py, Products/zms/zmsobject.py, Products/zms/zmssqldb.py, tests/test_rest_api.py
Introducing the REST API also introduced a major bug in resolution of internal links which lead to force links to parent-elements to stay in the context of the current-element:
https://github.com/zms-publishing/ZMS/commit/b6451b783e855c747ab01f6806b11fe4bc0ec722#diff-f187caa3a7d3bf290f667b9c8a6611ceb315d737d36985ddbebfdd7ad1f4cb41
During the analysis of this issue there was another issue with the zmsindex of a freshly initialized ZMS instance with default-xml-content.
The paths were duplicated (e.g. /myzmsx/content/content/e2, /myzmsx/content/e2). There can only be one correct object.
=> fix getLinkObj (was REST API)

Products/zms/_zreferableitem.py
Fix for Issue #172 
The content-class modelling gui shows a JS error on AJAX request for getting the breadcrumbs path of a default object path {$}
Due to: https://github.com/zms-publishing/ZMS/commit/566d24365c6c474faa6d6fac246cc7f5a978cbb3#diff-f187caa3a7d3bf290f667b9c8a6611ceb315d737d36985ddbebfdd7ad1f4cb41
=> Fix resolving error on default URL {$}

Products/zms/ZMSMetaobjManager.py, Products/zms/zpt/ZMSMetamodelProvider/manage_main_acquire.zpt
The acquisition of a content class behaves differently depending on
1. content class exists: a "overwriting" happens after a confirmation form (2nd step)
2. content class does not exist: "immediatly"  acquisition happens without conformation (in 1 step)
_Confrmation forms for "new" acquisitions:_
_Code location "overwrite"_
UX can be improved if gui behaves monotonously and show a confirmation form in any case.
Moreover the modal win should close after the confirmation (2nd) step and the base form should relaoded and show the resulting alert-message.
=> Improving meta-model import gui

Products/zms/conf/metaobj_manager/skin_zms5_base/standard_html.zpt, Products/zms/zpt/ZMSContainerObject/manage_main.zpt, Products/zms/zpt/ZMSObject/manage_main.zpt, Products/zms/zpt/ZMSSqlDb/manage_main.zpt
`body.data-level` as a ZMI-CSS customizing helper for depth-depending GUI details
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/308
Example:
```css
body.teaser_container:not(.ZMSAdministrator) select#layout option[value="list"] {
display: none;
}
body.teaser_container[data-level="1"]:not(.ZMSAdministrator) select#layout option[value="list"] {
display: unset;
}
```
=> ZMI: added level as data-attr to body-element

Products/zms/conf/metaobj_manager/com.zms.routing/__init__.py, Products/zms/standard.py
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/363
Umlaute in Dateinamen führen bei Mail-Versand per Formulator zu default-Names der Art "Unbenannte Anlage.dat"; durch den Verlust der Filext kann das File nicht bequem geöffnet werden.
Beim Processing durch Formulator bzw. ZMS bleibt der Filename durchgehend utf8 encodiert; einen Fehler war hier zu nicht identifizieren.
Ggf.  kann MIME1.0 (90er Jahre) das UTF8-Encoding der filenames nicht interpretieren bzw. provoziert einen default-Wert?
Eine einfache Lösung ist die Normalisierung des Dateinamens auf die 7bit-Zeichen mit der ZMS-Funktion standard.umlaut_quote()
1. https://github.com/idasm-unibe-ch/unibe-cms/pull/375/files
2. https://github.com/zms-publishing/ZMS/pull/176/files
Screenshots aus der Analyse
[1] In filedata erscheint …
=> Avoid umlauts in mail.attchmnt file names

.editorconfig, .vscode/settings.json, Products/zms/plugins/www/common/zmi_ace_editor.js
For homogeneous syntax Zope's editorconfig-files may be used. Some typical file types are added (css,html,js,xml)  to "4 space indentation".
Actually I am not sure about the "2 space indentation" for zpt/dtml, because the readibility is worse (but lines are shorter).
Refs:
INFO https://editorconfig.org/
VSCode-Ext: https://marketplace.visualstudio.com/items?itemName=EditorConfig.EditorConfig
=> Using Zope's .editorconfig

Products/zms/rest_api.py, Products/zms/zmsobject.py
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/394
To discuss: maybe the primary-lang value would be an alternative to the metatype-Keyord:
Hint: besides fix L129 there some whitespace fixes (trailing spaces etc.) automatically added
=> REST-API: avoid heterolingual titlealt reset

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/rest_api.py, Products/zms/zpt/ZMSIndex/manage_main.zpt
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/401
The ZMSIndex tree uses rest_api.get_child_nodes() to get the current node's children. It works like the sitemap tree with all requesting all child nodes. Actually the ZMSIndex tree is showing only ZMS-nodes by filtering the responsing JSON stream for ZMS-items.
It would be more efiicient to reduce the generation of the JSON stream only to ZMS nodes: this can be done by adding the parameter `meta_types=ZMS`  - at the right place, LINE 255
https://github.com/zms-publishing/ZMS/blob/8b0bd84e010ebfc9f450bb046b3682f87c3ad24c/Products/zms/zpt/ZMSIndex/manage_main.zpt#L254-L256
The screen-image shows transfer times of a JSON snippets: its 10-20x faster now
=> faster zmsindex-tree

Products/zms/ZMSItem.py, Products/zms/_multilangmanager.py, Products/zms/_objinputs.py
3rd-view templates may implicitly ask for the variable manage_lang and thus induce creation of a session object and a session cookie as a side-effect. So it should be determined, whether MultiLanguageManager.get_manage_lang()  ist called from ZMI or not. An added REQUEST-variable "is_zmi" may limit the session effect to ZMI. 
To be discussed: remove or use standard.isManagementInterface(request)
=>  Add REQUEST variable is_zmi to limit manage_lang determination

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Sitetree opens always with client root node, not the current content node (context).
This is a bug introduced by the migration from AJAX-XML to REST-API.
=> ZMI-Sitetree shall expand with current content node

Products/zms/ZMSMetamodelProvider.py, Products/zms/plugins/www/zmi.core.css, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt, Products/zms/zpt/ZMSMetamodelProvider/manage_readme_iframe.zpt
To use the content-model readme-file as styled html page, e.g. in a iframe, a new ZMSMetamodelProvider-template was added: 
Products/zms/zpt/ZMSMetamodelProvider/manage_readme_iframe.zpt
This template utilizes manage_readme.zpt and makes a zmi-html page of it.  
The readme-attribute gets (simmilar to the editorial gui) a button to call that readme-page.
=> Added readme html page

Products/zms/ZMSMetacmdProvider.py, Products/zms/zpt/ZMSMetacmdProvider/manage_main.zpt
Certain ZMS features (e.g. opensearch interface https://github.com/zms-publishing/ZMS/pull/203) needs the import of multiple config files; now this can be done in one step by importing the needed cmd-files as a selected stack,
=> Added multiple selection for metacmd import

Products/zms/_exportable.py
Recursive html export may lead to a type problem in the copy module because request keys are typed as dict_keys. 
```
>>>reductor(4)
Traceback (most recent call last):
File "<string>", line 1, in <module>
TypeError: cannot pickle 'dict_keys' object
```
In the end no html pages are generated.
=> Tix type problem of dict_keys on copy.copy

Products/zms/ZMSZCatalogConnector.py, Products/zms/conf/metacmd_manager/manage_zmsindex_reindex_paged/manage_zmsindex_reindex_paged.py
If the batch list is not returned as JSON the indexing process cannot controlled anymore by the JS frontend and will stop. The fix sets the setHeader() call as late as possible (to overwrite header setting due to content rendering etc.)
_[1] The batch-controlling JSON code it responded as `content-type = application/json`_
_[2] Certain circumstances may interfere with the content-type-Header and reset it to html; in this case the JS code for index-batching cannot process the resonse anymore_
_[3] rendering inner-page code may result in a change of the response format _
_ [4] patched code overwrites the header manipulation_
=> Paged Indexing: Ensure JSON Format on Response

Products/zms/_xmllib.py
fixed XML-Parsing
Ref: https://github.com/zms-publishing/ZMS/issues/230
=> MetaObj XML-Import: XML-Parsing of list-like attrs (e.g. autocomplete) may results in removed py-indents

Products/zms/rest_api.py
The fix prevents occasional Type-Errors with `json.dumps()` _Object of type Missing is not JSON serializable_:
Traceback:
```
2024-01-09 15:25:16 ERROR [waitress:435][waitress-0] Exception while serving /sites/content/++rest_api/zcatalog_adapter/elasticsearch_connector/zmsindex
Traceback (most recent call last):
File "/home/zope/instances/ZMS5_zeo_prod/venv/lib/python3.8/site-packages/waitress/channel.py", line 428, in service
task.service()
File "/home/zope/instances/ZMS5_zeo_prod/venv/lib/python3.8/site-packages/waitress/task.py", line 168, in service
self.execute()
File "/home/zope/instances/ZMS5_zeo_prod/venv/lib/python3.8/site-packages/waitress/task.py", line 434, in execute
app_iter = self.channel.server.application(environ, start_response)
File …
```
=> REST API: force json values to string

Products/zms/ZMSMetaobjManager.py, Products/zms/ZMSZCatalogAdapter.py, Products/zms/_zmi_actions_util.py, Products/zms/zpt/ZMSZCatalogAdapter/manage_main.zpt
Ref: https://github.com/idasm-unibe-ch/unibe-cms-opensearch/issues/21
The indexing filter consists of python code that works with two parameters:
1. context is the currently iterated object to be indexed
2. meta_ids is the list of content-classes that should be indexed.
The applied code can define rules based on the context's attributes values whether indexing shall happen or not. The returning value of the filter rules must be True or False. A simple example will illustrate how it can be applied; the intention would be "Do not index any inactive node, it's descendants and nodes having type-attribute set to 'Resource'".
```
##
return (context.meta_id in meta_ids) \
and not [ob for ob in context.breadcrumbs_obj_path() if not ob.isActive(context.REQUEST)] \
and not …
```
=> Catalog-Adapter: custom filter-function

Products/zms/zpt/ZMSObject/input_fields.zpt
This PR tries to improve usability on Refresh Catalog Item of a content object if its UID is missing in ZMSIndex.
The page gets now a refresh by javascript again after the event is triggered on red button click -> the cataloged UID is shown in normal black afterwards and not in red with button anymore, which confuses the editors.
=> fix(zms-index): Show instant change on refresh catalog

Products/zms/zmssqldb.py
The sql grid may not provide the details-link if pk is configured not invisible for the grid view.
=> fix(sql-gui): add pk-value to grid-context

Products/zms/_confmanager.py, Products/zms/_objattrs.py, Products/zms/zpt/ZMSContainerObject/manage_system.zpt
Ref:
https://github.com/zms-publishing/ZMS/pull/255
https://github.com/zopefoundation/Zope/issues/311
ZEXP-data transfer will be blocked, if content from branch #fb_sys_conf_repo (PR #255) is transferred to a ZMS running without the new config-manager. The code changes shall avoid broken object-error on iterating Zope nodes for ZMI.
```log
2024-02-28 08:13:10 ERROR [waitress:357][waitress-0] Exception while serving /VirtualHostBase/https/zms5.sntl-live.zms.hosting:443/VirtualHostRoot/sites/manage_importObject
Traceback (most recent call last):
File "/home/zope/virtualenv_zms5/lib/python3.8/site-packages/waitress/channel.py", line 350, in service
task.service()
File "/home/zope/virtualenv_zms5/lib/python3.8/site-packages/waitress/task.py", line 171, in service
self.execute()
File …
```
=> ZMI: Prevent Error on Iterating over Broken Zope-Objects

Products/zms/ZMSZCatalogAdapter.py
Considers client specific page models in a multisite
=> ZCatalog: Meta-Ids in context of current node (DESY)

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Ref: https://github.com/zms-publishing/ZMS/issues/265
A changed starting node in browse obj dialog may be ignored, if DOM contains more than one url-select-forms
This can happen in a modal dialog where a similar form already exists in DOM (in case of Usermanagement-GUI prepared with display:none).
=> URL input field: Object tree does not open the UID entered

Products/zms/standard.py
compatibility with Zope-lastest
=> Fix TypeError: 'generator' object is not subscriptable

Products/zms/_accessmanager.py, Products/zms/configure.zcml
Added a ZCML snippet to ZMS-configure.zcml for publishing ZMI CSS/JS-resources.
Since https://github.com/zopefoundation/Zope/pull/1166 general GUI resources are not public anymore but limited to the `ViewManagementScreensPermission`. If using bootstrap.css or fontawesome for the website-design, these resources can get accessed by changing its permisson by adding the path to a overrides.zcml for ZMS:
```
<browser:resourceDirectory
name="zmi"
directory="~/virtualenv_demo/src/zope/src/zmi/styles/resources"
permission="zope.Public" />
```
[overrides.zip](https://github.com/zms-publishing/ZMS/files/15149540/overrides.zip)
The `directory`-directive has to be adopted to the local installation path (this is not convenient!).
A late Zope-PR https://github.com/zopefoundation/Zope/pull/1204 may have …
=> Publishing ZMI CSS/JS-Resources

Products/zms/ZMSZCatalogAdapter.py, Products/zms/conf/metaobj_manager/com.zms.catalog.opensearch/opensearch_connector/manage_opensearch_schematize.py
Ref: https://github.com/idasm-unibe-ch/unibe-cms-opensearch/issues/51#issuecomment-2079237881
A date is considered as "ZonedDateTime"
```js
GET /_scripts/painless/_execute
{
"script": {
"source": """
// ZonedDateTime.parse(params.x).isBefore(ZonedDateTime.parse(params.y))
ZonedDateTime.parse('2022-05-15T10:30:00+00:00')
""",
"params": {
"x": "2022-05-15T10:30:00+00:00",
"y": "2024-05-15T10:30:00+00:00"
}
}
}
```
It's not clear, which Py-type should be transfered ny opensearch-py:
Test-Snippet painless-script for comparing dates (still not working):
```js
GET myzmsx11/_search
{
"size": 10,
"from":0,
"query": {
"script_score": {
"query": {
"query_string": {
"query": "Extra"
}
},
"script": {
"lang":"painless",
"source": """
int wght = 1;
ZonedDateTime limit_dt = …
```
=> Search: add change_dt/created_dt as default fields

Products/zms/ZMSZCatalogAdapter.py, Products/zms/_versionmanager.py
Ref: https://github.com/idasm-unibe-ch/unibe-cms-opensearch/issues/50
Reindexing does not refer to the correct node. This fix shall identify the context's page container and/or the lowest content class of the path to be indexed.
The first commit improves the sponateous page contaner indexing on INSERT.
[1]
But there is a problem with INSERT of Pageelements: it does not trigger the container to be indexed because the context-breadcrumb misses the last level 
[2]
If an existing pageelement is saved, reindexing works
[3]
the refactored `reindex_node`-Function tries to identify the node/context's page container and in special cases (e.g. ZMSFile) both nodes have to be reindexed. 
The current code status does not reindex correctly on inserting a pagelement [3]. Supposingly it is not a race …
=> Ensure Reindexing Context's Page Container on Change/Insert

Products/zms/ZMSZCatalogAdapter.py
Ref: 
1. https://github.com/zms-publishing/ZMS/commit/936b091e6317f138dba4999999f79b9c7f80f140 
2. https://github.com/zms-publishing/ZMS/issues/278
Result:
1 Now page content is aggreated the same way for all cases (fullindex, change, insert).
2. In case of indexed attributes (e.g. _standard_html_) are not filled with expected text, delete (misconfigured) search-adapters and start full reindex.
URLs:
1. CONFIG https://edit.cmstest2.unibe.ch/unibe/content/zcatalog_adapter/manage_main
2. TEST https://edit.cmstest2.unibe.ch/unibe/portal/fak_vetmedizin/a_dept_dkv/inst_kleintier/content/e18883/e750745/e750831/manage_main?lang=ger
3. INDEX https://idcmsosearchint01.id-sys.unibe.ch/app/dev_tools#/console
_ad 3: Snippets_
```
GET /unibe/_search
{
"query": {
"match_phrase": {
"uid": {
"query": …
```
=> Monotonize aggregating page-content by sequencing page-elements' standard_html

Products/zms/zopeutil.py, tests/test_zopeutil.py
default manage permissions for native zope-objects with id matching 'manage(.*?)':
'Access contents information' and 'View' for 'Authenticated'
=> default manage permissions

Products/zms/zmscustom.py, Products/zms/zpt/ZMSRecordSet/main.zpt
The fix tries to ensure that qindex from absolute result-set points at the right element in the filtered and sorted result-set.
=> [idasm-unibe-ch/unibe-cms-opensearch] Toptreffer: Fehler beim Filtern (Issue #88)

Products/zms/plugins/www/zmi.core.css, Products/zms/zmsobject.py, Products/zms/zpt/common/zmi_breadcrumbs_obj_path.zpt
Ref: https://github.com/zms-publishing/ZMS/issues/295
`getattr()`  does not work with complex zms-objects containing an sub-object named like a python keywords/function, like 'items':
https://github.com/zms-publishing/ZMS/issues/295#issuecomment-2248933656
=> fix 'items' as object-id in breadcrumbs_obj_path

Products/zms/_objattrs.py
The Browser provides datetime-values by "local-time". Computing these tuples to seconds and the to a python struc_time to allow datetime comparison the daylight saving time (DST), actally 1 hour, will be ignored and the result will be standard-time.
So, in case of  DST one hour has to be subtracted:
```py
- dt = datetime.datetime.fromtimestamp(time.mktime(value))
+ dt = datetime.datetime.fromtimestamp(time.mktime(value) - (time.daylight * 3600))
```
Another option would be to inject the `tm_isdst ` into the time tuple:
Ref: https://stackoverflow.com/questions/1697815/how-do-you-convert-a-time-struct-time-object-into-a-datetime-object
Any comments?
=> Activity during Daylight Saving Times (CEST)

Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt, Products/zms/zpt/ZMSMetamodelProvider/manage_metas.zpt
While analysing performance in context of https://github.com/zms-publishing/ZMS/issues/316 with very large meta-attribute-lists, it's redundancy reveals as amplifier of the latency. 
According to the idea of iterative row-inserting of a DOM-clone, now the GUI primarily provides just minimized select-lists with only one option and that is the saved/selected type-value of the meta-attribute. 
To get the full-featured select-lists to any meta-attribute the frontend-JS now clones the select-list of the insertable row (last row) into the primarily minimized select-lists. So ZMS iterates the meta-attributes only once and HTML-Code gets much smaller. Thus GUI gets about 3x faster.
[1] _Minimized select-list for any item_
https://github.com/zms-publishing/ZMS/blob/d89fa772e23cccf01b649f02478d17b9e …
=> ZMI: Improved performance of meta-attribute-table

Products/zms/_cachemanager.py, Products/zms/_exportable.py, Products/zms/_globals.py, Products/zms/_objattrs.py, Products/zms/_pathhandler.py, Products/zms/_textformatmanager.py, Products/zms/_zreferableitem.py, Products/zms/standard.py, Products/zms/zmslinkelement.py, Products/zms/zmsobject.py
Using a function call for getting a "fake" REQUEST object as a fallback for the headless mode will result in a lot of executions, even in cases that do not need this fallback for a proper work. Especially caching creates a lot of redundant executions slowing down the system.  
So I tried to set that object only once a global variable in the _globals module. As a side effect the it gets private. 
The execution now is limited to startup
_[1] Screen image: massive repetitions of creating fake requests objects_
_[2] Screen image: creating fake requests object only once on startup_
_[3]  the function now logs its latency and thus indicates when it is executed_
```py
def create_headless_http_request():
"""
Returns a ZPublisher.HTTPRequest object to be used in headless mode.
"""
import logging …
```
=> Refact headless http request as global var

Products/zms/_cachemanager.py, Products/zms/_exportable.py, Products/zms/_globals.py, Products/zms/_objattrs.py, Products/zms/_pathhandler.py, Products/zms/_textformatmanager.py, Products/zms/_zreferableitem.py, Products/zms/standard.py, Products/zms/zmslinkelement.py, Products/zms/zmsobject.py
- Superseed  https://github.com/zms-publishing/ZMS/pull/321
- needs new import: `from zope.globalrequest import getRequest`
- Standard fallback: getattr(self, 'REQUEST', getRequest())
- for headless mode: set REQUEST globally by `zope.globalrequest.setRequest()`
- **Still open**:  primaryLanguage problem with `__bobo_traverse__` : RESTAPI-test still fails; check if headless mode works without primaryLanguage fallback 
https://github.com/zms-publishing/ZMS/blob/54e8ef59d427e09b160101e2fc11b4d2ddbf3e03/Products/zms/_pathhandler.py#L145
=> Fix headless mode using zope.globalrequest.getRequest()

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Ensure backwards compatibility of `ZMS.menulock` value, because https://github.com/zms-publishing/ZMS/commit/8945bffff55b8436802812089e61aea7047ba732 introduced a new handling of menu pin to stay in context on save -> was `true|false` before and is now integer (`1|0`).
Without this fix a user with a former `true|false` in localstorage gets this scary Waitress server error on save:
```
2024-10-16 20:12:01 ERROR [waitress:435][waitress-2] Exception while serving /unibe/portal/content/e1200/e1360/manage_changeProperties
Traceback (most recent call last):
File "/unibe-cms/backend/zope/src/ZPublisher/Converters.py", line 94, in field2int
return int(v)
^^^^^^
ValueError: invalid literal for int() with base 10: 'true' 
```
=> fix(menulock): Convert localstorage value into int

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
If ZMI shows html-code containing iframes as content-blocks the ZMI assumes the sitemap-frameset is active - and thus the sitemap cannot toggle anymore. The JS-change additionally checks the name "manage_menu"
=> fix: sitemap btn (zhref)

Products/zms/_copysupport.py
Copying a link-objects thats uses the embed feature results in attributes error on renaming with `manage_renameObject()`:
* Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/764
Any childnodes in case of  link embedding have to be ignored for calling manage_renameObject(). The approach of the change shall make sure that the parent-node of the current childNode is the current node (which is ot in case of embedding). @zmsdev:  any other idea?
=> Fix: Ignore link-embedded childnodes for obj-copy

Products/zms/_copysupport.py
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/763
Do not reset object-state to new, if workflow is inactive (autocommit)
=> Copy & Paste: objects not visible in live view in alternative language

Products/zms/_mediadb.py
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/659
The mediadb module creates a text-response "file not found" in case a media-file cannot be located in the filesystem; this comes with the HTTP status code 200. Actually 404 is more appropriate.
Actually 404 is more appropriate.
=> Set status-code 404 in case media file not found

Products/zms/ZMSZCatalogAdapter.py
Ref: 
1. https://github.com/idasm-unibe-ch/unibe-cms/issues/776#issuecomment-2446989138
2. https://github.com/zms-publishing/ZMS/issues/278
=> OpenSearch: Unindex/Reindex depending on node visibility #776

Products/zms/conf/metaobj_manager/com.zms.foundation/ZMS/interface_permalinks.zpt, Products/zms/zpt/ZMSFilterManager/manage_main.zpt, Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt, Products/zms/zpt/ZMSMetamodelProvider/manage_metas.zpt, Products/zms/zpt/ZMSRecordSet/grid.zpt
Ref: https://github.com/zms-publishing/ZMS/issues/346
The CSS class `row_insert` leads to disabling the table row because now this is applied as a form-set cloning-template for multiple inserts. I added a quickfix by renaming the `tr.row_insert` and prepared the the JS for multiple row inserting.
HINT: multiple row inserting needs a modification of the `retrieve()`-function for it's request-variable processing (as iteration over indexed rows)
https://github.com/zms-publishing/ZMS/blob/c980eaf4b21d46bdd4a8127bf5a54a065c19f0e6/Products/zms/zmscustom.py#L557-L565
=> ZMSRecordSet: Fixed insertion of new records in grid-view

Products/zms/ZMSZCatalogAdapter.py
Problem (reported by RFH): 
Content-blocks that create a http `redirect` by template-code or dtml-code placed in a ZMSTextarea-block will stop incremental indexing of the content.
_[1] Inplace-redirect content-classes stop reindexing ..._
_[2] .. as well as a redirecting dtml/tal-snippet in a text-block (difficult to find!!!)_
=> Prevent in-place redirecting during content-indexing

Products/zms/_objattrs.py
`ZMS_INSERT` is set to `None` in request object by `_versionmanager.VersionItem.commitObjChanges()`
https://github.com/zms-publishing/ZMS/blob/927f1051116e857ad7858c5c9f33060ccba1c03b/Products/zms/_versionmanager.py#L628-L635
-> this remains in subsequent processing of this request object
-> this may provoke side effects
This change handles both situations: `request['ZMS_INSERT']=None` and `request['ZMS_INSERT']=unset`
To be checked: Other occurrences of such unset checks of `ZMS_INSERT`
Refs: https://github.com/idasm-unibe-ch/unibe-cms/pull/824/commits/ac7f200721dea530ff698327f760f04b6e7c9890
=> refact(attr-is-modified): Changed ZMS_INSERT condition

Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
The manage-template renders lang-var names that incidentally start with the meta-id:
GUI should avoid the false positive lang-var names:
=> Fix metaobj lang-vars name splitting

Products/zms/zms.py
This is a follow-up for
- #314
- [feat(ZMS): add minimal_init flag to initZMS](https://github.com/zms-publishing/ZMS/pull/314/commits/b7ad7d72fa141b6f098ccda789c00d7e6880a95f)
Fixes https://github.com/idasm-unibe-ch/unibe-cms/issues/843
=> fix(initZMS): Added missing minimal_init parameter

Products/zms/_zmi_actions_util.py, Products/zms/plugins/www/ZMS/zmi_body_content_search.js, Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/plugins/www/zmi.core.js, Products/zms/zpt/ZMS/manage_users.zpt
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/840
The action list usually shows interactive "actions" on top of the context-Menu:
But when navigating via tree the PAGEELEMENT-context-menu does not render the context-actions:
Actually in these cases `context is None` and thus `_zmi_actions_util.zmi_actions()` will not deliver any action-items with `zmi_basic_actions()`. 
The quickfix ensures that actions are listed:
https://github.com/zms-publishing/ZMS/pull/364/files#diff-8f772aba96b1d54c6bdd2ed89440ead1c6985d8db1742f235889ba70affd2dedR59-R60
```py
if context is None:
context = container
```
@zmsdev : The dilemma seems to start with 
https://github.com/zms-publishing/ZMS/blob/b025525538c9dae7fc323b0308fa682ee79342ec/Products/zms/zmscontainerobject.py#L587
```py
context = None …
```
=> Fix: Action-List Cut-Off

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js
Refs: 
* https://github.com/sntl-projects/nginx-sso/issues/10
* https://github.com/idasm-unibe-ch/unibe-cms/issues/847
AJAX-requests may not ensure the id-token refresh in a azure-env. The JS-fix starts a page reload in case of 401-auth-error for refreshing the outdated id-token.
=> 401-fallback to ajax request in navtree and action-menu

Products/zms/plugins/www/object/manage_menu.js, Products/zms/plugins/www/zmi.core.js
Refs:
https://github.com/zms-publishing/ZMS/commit/b5b41698c652f33d349d2de427e392dd9b3ec5f7
idasm-unibe-ch/unibe-cms#847
sntl-projects/nginx-sso#10
The HTMX induced ZMI loading in manage_main-frame may need a normal request for refreshing SSO tokens:
Hint: Some unnecessary console verbosity has also been removed.
=> added more 401 fallbacks to ajax requests (#367)

Products/zms/plugins/www/object/manage_menu.js, Products/zms/plugins/www/zmi.js, Products/zms/zpt/common/zmi_html_head.zpt
Ref: 
* https://github.com/idasm-unibe-ch/unibe-cms/issues/860
* https://htmx.org/quirks/#history-can-be-tricky
To inialize ZMI the standard history handling is needed and prevent the htmx:history-cache
=> ZMI: history.back issue with htmx

Products/zms/zpt/common/zmi_html_head.zpt
The Zope API function `absolute_path()` may cut - if not called by generic URL -  the object-path to the common-folder, so that` restrictedTraverse()` cannot not verify the object anymore. As a consequence the ZMI will not be enhanced by "additional" JS/CSS (that is configured explicitly).
Ref: https://github.com/zms-publishing/ZMS/commit/573b69a4aa507368c9e4b9936ead46542a3e9fc8
=> zmi: linking "added" resources via physical path

Products/zms/plugins/www/zmi.js, Products/zms/zpt/common/zmi_html_head.zpt
Ref: https://github.com/idasm-unibe-ch/unibe-cms/issues/860#issuecomment-2697396857
The change ensure that ZMI will be intialized on browser-history navigation. It refers mainly to the contextual dropdown-menus that may provoke the follwoing JS error:
```
Uncaught TypeError: Cannot read properties of null (reading 'setAttribute')
at Object.onLoad (popper.js:1211:10)
at popper.js:2521:25
at Array.forEach (<anonymous>)
at new t (popper.js:2519:20)
at e.show (dropdown.js:176:22)
at e.toggle (dropdown.js:126:10)
at HTMLButtonElement.<anonymous> (dropdown.js:367:14)
at S.each (jquery-3.5.1.min.js:2:2976)
at S.fn.init.each (jquery-3.5.1.min.js:2:1454)
at t._jQueryInterface [as dropdown] (dropdown.js:353:17)
```
Hint: the htmx-meta is removed again, because the meta seems not to contribute to …
=> zmi: htmx-compatible execution of $ZMI.runReady() on history.events

Products/zms/ZMSMetaobjManager.py, Products/zms/zopeutil.py
Fixed zopeutil.addExternalMethod:
Problem when traversing the hierarchy, Application-Object does not seem to know getParentNode() anymore.
Same fix as in zopeutil.readData()
Could be refactored in a better way.
=> fixed addExternalMethod

Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/rest_api.py
Ref: https://github.com/zms-publishing/ZMS/issues/335
The content-preview in the content tree may not be JSONified.
_Screen-A:  Navtree shows a reduced peview of the content object as plain text; it is "codeless" rendered by pure CSS_
_Screen-B: Recordsets that contain blob-fields cannot be transformed to a text stream_
=> normalize rest api obj data for preview

Products/zms/ZMSItem.py, Products/zms/zpt/ZMS/manage_customize.zpt, Products/zms/zpt/ZMSContainerObject/manage_main.zpt, Products/zms/zpt/ZMSObject/manage_main.zpt, Products/zms/zpt/ZMSSqlDb/manage_main.zpt, Products/zms/zpt/common/zmi_tabs.zpt
_Background_: If the ZMI body-element do not set the hx-push-url-attribute, some script-initialiized gui-elements like context-menu may show up incomplete [1]. So this PR addresses the same problem like PR#385, but seems to an alternative to  [2]:
Instead of declaring the hx-push-url by HTML/TAL-templates, like in PR#385, it can be done as a RESPONSE-header parameter `HX-Push-Url` [3]. 
The important difference to the HTML-approach: the RESPONSE-header parameter `HX-Push-Url`  does not work with the simple "true" value, but it needs the URL. Therefore "REQUEST_URI" is applied: https://github.com/zms-publishing/ZMS/pull/386/commits/f1f7be6e5928bf65e54cfb7191e8280af6e2dc08
References:
1. https://github.com/idasm-unibe-ch/unibe-cms/issues/860#issuecomment-2721985426
2. …
=> Generalizing hx-push-url attribute: 2. by RESPONSE-header

Products/zms/ZMSMetaobjManager.py, Products/zms/rest_api.py, Products/zms/zpt/ZMS/openapi_yaml.zpt
This PR ~~adds a new endpoint `get_content_objects`~~ extends `list_tree_nodes` to retrieve the ids of content objects filtered by given `meta_id`, e.g.
```url
http://127.0.0.1:8081/unibe/portal/content/e1006/e1061/e3118/e11588/++rest_api/list_tree_nodes?meta_id=ZMSTable
```
- The return value is a list for further processing, e.g.
```json
[
{
"id": "e1137491",
"meta_id": "ZMSTable",
"uid": "uid:211a1d31-a05b-4eb3-89d2-e07cb9a79301",
"getPath": "/unibe/portal/content/e1006/e855118/e855497/e1099265/e1137489/e1137491"
},
{
"id": "e1137574",
"meta_id": "ZMSTable",
"uid": "uid:bd056c0f-01d0-440f-91dd-649b41129621",
"getPath": "/unibe/portal/content/e1006/e855118/e855497/e1099265/e1137544/pane1137545/e1137574"
}
]
```
- The request path is handled in a slightly different way than for the …
=> RESTAPI: List tree nodes based on ZMSIndex filtered by meta_id

Products/zms/zpt/ZMSMetamodelProvider/manage_main.zpt
The input value to filter metaobjs should not be case-sensitive to match all names containing a substring.
https://stackoverflow.com/questions/8746882/jquery-contains-selector-uppercase-and-lower-case-issue
=> feat(metaobj): Made tablefilter case insensitive

Products/zms/_copysupport.py
References:
* https://github.com/zms-publishing/ZMS/issues/408
* https://github.com/idasm-unibe-ch/unibe-cms/issues/991
The fix shall make sure that only inserted nodes are affected with status changes
=> Workflow: normalize_ids_after_copy() resets collateral status on copy/paste

Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSLinkElement/__init__.py, Products/zms/conf/metaobj_manager/com.zms.foundation/ZMSLinkElement/inferface0.zpt, Products/zms/plugins/www/bootstrap/plugin/bootstrap.plugin.zmi.js, Products/zms/plugins/www/zmi.core.js
References
https://github.com/idasm-unibe-ch/unibe-cms/pull/1012
https://github.com/idasm-unibe-ch/unibe-cms/issues/998
Last changes of ZMSLinkElement's url-input-GUI of ZMSLinkElement are generalized to the core-function that creates url-input-fields:
* https://github.com/zms-publishing/ZMS/commit/647a6231bb4e34f41c20ab41576a74986d15a80a
* https://github.com/zms-publishing/ZMS/commit/06f8d7981147c1848ddec0cff1fd8505c21aea9c
Goal is to transfer the value of the Link's lang-parameter into the lang-selector modal-win.
=> update zmiBrowseObjs and ZMSLinkElement 5.2
